POST http://localhost:5228/api/Airline
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NzQyMGQwMy1lOGIxLTRjOTctOTFkZC01ZTI3Mjk2YmFlNzEiLCJnaXZlbl9uYW1lIjoiR2l0aHViIiwiZmFtaWx5X25hbWUiOiJUZXN0IiwianRpIjoiNWYwYzhhYmItNDQwOS00YTgyLWJjZjItMTE3MWRjNzVmODk2IiwiZXhwIjoxNjc5MzM2MjM1LCJpc3MiOiJBZGVtQ0xLIiwiYXVkIjoiQWRlbUNMSyJ9.3JSdhBx4K_178uT0BZ63f-_ZMl2tPZDvQcvwbgX1kg5w4wGa8-NNNFzPk-AyoXOtL8hb4lxF2bjppLfr7XbqPA

{
  "name": "Anadolu Jet",
  "iataCode": "TK",
  "icaoCode": "THY",
  "callsign": "ANADOLUJET",
  "code": "235",
  "website": "https://www.anadolujet.com/tr",
  "address": {
    "cityId": "fb18a2cc-34a7-470b-a347-cfc327fa1f07"
  },
  "aircraftIds": [
    ""
  ]
}