GET http://localhost:5228/api/aircrafts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzOWFhNDIxYi04OGM4LTQ4MjgtOTc2Ni0wNWRhN2FhNDNiZGUiLCJnaXZlbl9uYW1lIjoiVGVzdCIsImZhbWlseV9uYW1lIjoiVXNlciIsImp0aSI6IjJlNWYyZTQwLTJkNjMtNGJmZS1hODQxLWZiZTQxZmU4ZjI1YSIsImV4cCI6MTY3NTE5MjAyNSwiaXNzIjoiQWRlbUNMSyIsImF1ZCI6IkFkZW1DTEsifQ.UnxU1Nk77iV4KKNQn7VhdLBfcVJJHJ398oksRwDF_wMq4P49yTfbpwF0ID3QanplsG11LblhFaNFqw797D2PgQ