GET http://localhost:5228/api/aircrafts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzOWFhNDIxYi04OGM4LTQ4MjgtOTc2Ni0wNWRhN2FhNDNiZGUiLCJnaXZlbl9uYW1lIjoiVGVzdCIsImZhbWlseV9uYW1lIjoiVXNlciIsImp0aSI6ImY4NTM3NjE1LTU4NDEtNDE5NC1iOWJmLThlMjM2MDIzYjY5OCIsImV4cCI6MTY3NDczNjIzOCwiaXNzIjoiQWRlbUNMSyIsImF1ZCI6IkFkZW1DTEsifQ.xPW-uwUxguFoYe7dvBANFZcpCJMEoiDAi6WLqfiVFTRqwyIbDpE-yIDE5b_zzH-i0bsCo9wQWpG2YmohsAUyCw