POST http://localhost:5228/api/Airport
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NzQyMGQwMy1lOGIxLTRjOTctOTFkZC01ZTI3Mjk2YmFlNzEiLCJnaXZlbl9uYW1lIjoiR2l0aHViIiwiZmFtaWx5X25hbWUiOiJUZXN0IiwianRpIjoiYWJhNDRkNGQtOWVmOC00MDI2LTg3MmEtMmFlOTMzYjVhNGEzIiwiZXhwIjoxNjc4Nzk2MjIyLCJpc3MiOiJBZGVtQ0xLIiwiYXVkIjoiQWRlbUNMSyJ9.7c3DPLPWxCD5dj0neXyfrU-WV9UYXacbUuPDqCNCT3io6GjBi-fGjuLk8GKIzKuUMKPoLAqjRH6OCAHOpVFvMQ

{
  "name": "Katowice Uluslararası Havalimanı",
  "cityId": "bc55a6d8-e866-4013-b210-36f415aff0ec",
  "iataCode": "KTW",
  "icaoCode": "EPKT",
  "latitude": 48.78589445854278,
  "longitude": 44.34543763858307,
  "timezone": "GMT+01:00"
}
