GET http://localhost:5228/api/airport/search?query=S


###
GET http://localhost:5228/api/Airport
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NzQyMGQwMy1lOGIxLTRjOTctOTFkZC01ZTI3Mjk2YmFlNzEiLCJnaXZlbl9uYW1lIjoiR2l0aHViIiwiZmFtaWx5X25hbWUiOiJUZXN0IiwianRpIjoiZDEwZTEyODYtZTRlMS00YmFhLThhZjktNDdiN2Y4MjZhNzJmIiwiZXhwIjoxNjc3NDg2Nzg3LCJpc3MiOiJBZGVtQ0xLIiwiYXVkIjoiQWRlbUNMSyJ9.rYCbGnhCjXMy1-qzVvO4-ziB8m1MwlCw3UVnSVJs4K-BpJoeqYybMtCe-cS8w2eG8bvEJQSTPvvbSWlQmGuANQ