POST http://localhost:5228/api/Seat
Content-Type: application/json

{
  "seatNumber": "10F",
  "aircraftId": "d62a5ff7-0473-4f26-8906-a4b4083ba6b4",
  "flightId": "7cae1ba1-6863-4e53-bb37-0a383c264190",
  "seatClass": 0,
  "seatStatus": 0
}