POST http://localhost:5228/api/Flight
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NzQyMGQwMy1lOGIxLTRjOTctOTFkZC01ZTI3Mjk2YmFlNzEiLCJnaXZlbl9uYW1lIjoiR2l0aHViIiwiZmFtaWx5X25hbWUiOiJUZXN0IiwianRpIjoiYmVjYzRjZTAtZjZjMi00ODMxLTg2ZTAtZTA1Y2E1NzIyN2NmIiwiZXhwIjoxNjc3MDEzNTU5LCJpc3MiOiJBZGVtQ0xLIiwiYXVkIjoiQWRlbUNMSyJ9.rEYlJb_iX9fI9VjuVm1wHjHvtc_iqViAvGVRHgA-83KkIMFwHJ1JHZ4KmI-h12HEvzI7LLG44AXpV6NfCUUBvw

{
  "flightNumber": "AI000002",
  "scheduledDeparture": "2023-03-03T16:13:34.240Z",
  "scheduledArrival": "2023-03-03T18:13:34.240Z",
  "status": 0,
  "type": 0,
  "actualDeparture": null,
  "actualArrival": null,
  "aircraftId": "0a3901f2-cf62-441e-9ae8-0d3a9e5059c2",
  "departureAirportId": "36c66a4f-dc74-4c70-8823-e02583cfe285",
  "arrivalAirportId": "457dc6e0-c585-4025-912c-3101435270ff",
  "priceId": "f0b4f0f9-496f-4a9f-a60e-bfc63eb91f04"
}
