POST http://localhost:5228/api/Flight
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NzQyMGQwMy1lOGIxLTRjOTctOTFkZC01ZTI3Mjk2YmFlNzEiLCJnaXZlbl9uYW1lIjoiR2l0aHViIiwiZmFtaWx5X25hbWUiOiJUZXN0IiwianRpIjoiNWYwYzhhYmItNDQwOS00YTgyLWJjZjItMTE3MWRjNzVmODk2IiwiZXhwIjoxNjc5MzM2MjM1LCJpc3MiOiJBZGVtQ0xLIiwiYXVkIjoiQWRlbUNMSyJ9.3JSdhBx4K_178uT0BZ63f-_ZMl2tPZDvQcvwbgX1kg5w4wGa8-NNNFzPk-AyoXOtL8hb4lxF2bjppLfr7XbqPA

{
  "flightNumber": "AI000003",
  "scheduledDeparture": "2023-03-24T16:30:34.240Z",
  "scheduledArrival": "2023-03-24T17:30:34.240Z",
  "status": 0,
  "type": 1,
  "actualDeparture": null,
  "actualArrival": null,
  "aircraftId": "e182aaa1-130a-4418-a537-f634b104a3df",
  "departureAirportId": "457dc6e0-c585-4025-912c-3101435270ff",
  "arrivalAirportId": "a5cf68f9-23a3-4385-8bcb-bbd586a4d23b",
  "economyPriceId": "4d28ee7e-3c35-490a-a64a-6703a4f0da7b",
  "comfortPriceId": "24748793-1d19-400e-92d3-217d171f07dc",
  "businessPriceId": "75337c5f-8ae2-4cce-8bc8-3ded8136fb49"
}


