POST http://localhost:5228/api/Price
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NzQyMGQwMy1lOGIxLTRjOTctOTFkZC01ZTI3Mjk2YmFlNzEiLCJnaXZlbl9uYW1lIjoiR2l0aHViIiwiZmFtaWx5X25hbWUiOiJUZXN0IiwianRpIjoiOTFiOGM2ZjAtZTdmYy00NDY2LWE4MTUtZGQ5ZTI5YzQzOTlkIiwiZXhwIjoxNjc3MDE3NjcwLCJpc3MiOiJBZGVtQ0xLIiwiYXVkIjoiQWRlbUNMSyJ9.vmUUt94iM8tS_y9RSVREd0BsUf3dahjvUd2dXeLnRMz-aqyMlj6IXW5oEbFBAvzlsrUFVTHnLnWRYxlJsK1mgw

{
  "amount": 1,
  "currency": 0,
  "pricing": {
    "baseCost": 100,
    "markupPercentage": 10,
    "demandMultiplier": 1,
    "competitionMultiplier": 0.9,
    "seasonalMultiplier": 1.3,
    "lengthMultiplier": 1.5,
    "classMultiplier": 1.2
  }
}